## Logic Config  
ranks:
  wood:
    explosionRadius: 1  
    material: 17
  stone:
    material: 1


## PlayerData Config

## BigBertha

kickWarnings: 3
botid: "b0dafd24ee35a477"
botname: "Chomsky"
devmode:
  server: false
eggnade:
  explosionRadius: 0
