## Logic Config  
ranks:
  wood:
    rankPerkExplosionRadius: 1  
    rankPerkMaterial: 17


## PlayerData Config

## BigBertha

kickWarnings: 3
botid: "b0dafd24ee35a477"
botname: "Chomsky"
devmode:
  server: false

